#%RAML 1.0
title: Users API

/getUsers:
  get:
    responses:
      200:
        body:
            application/json: 
              example: !include examples/user-details.json
      500:
        body:
          application/json:
            example: !include examples/500-system-error.json              
/getUser:
  /{username}:
    get:
      responses:
        200:
          body:
              application/json: 
                example: example/user-details.json
        404:
          body:
            application/json:
              example: !include examples/404-user-not-found.json
        500:
          body:
            application/json:
              example: !include examples/500-system-error.json  